---
title: "New Zealand Retail sales by region (2012)"
author: "Victor"
date: "3 octobre 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages used: 

```{r}
library(topogram)
library(sf)
library(rmapshaper)
```



## Retail data

Data came from [Stats NZ](https://datafinder.stats.govt.nz/). You can download shapes [here](https://datafinder.stats.govt.nz/layer/95458-retail-trade-sales-per-capita-by-region-2012-2017/data/), select export shapefile with WGS 84 projection.


```{r}
# read {sf} object
nz_retail <- read_sf("datas/retail-trade-sales-per-capita-by-region-2012-2017.shp")
# simplify geometries
nz_retail <- ms_simplify(nz_retail)
```



## Cartogram

```{r}
topogram(
  shape = nz_retail,
  value = c("Per_capita", "Per_capi_1", "Per_capi_2", "Per_capi_3",
            "Per_capi_4", "Per_capi_5", "Total_trad", "Total_tr_1", "Total_tr_2",
            "Total_tr_3"),
  tooltip_label = ~REGC2018_V, 
  format_value = ",.0f",
  n_iteration = 20
)%>% add_legend(
  title = "",
  title_width = 200,
  orientation = "vertical",
  label_format = ".2s"
)
```







